### ISSUE TITLE
Add SBUS support

### ISSUE THREAD

**Issue by skorokithakis** [wireless-rc-adapter/wireless-rc-adapter#12]
It would be great if we could connect receivers that used SBUS, as those are the most common nowadays. I have some Arduino code that reads the channels that I could post if you're interested, as well as a schematic for a simple inverter board that works very well.

**Comment by gregnau** [comment]
I have done it already, it will come with the next release later this year.

**Comment by skorokithakis** [comment]
Can you tell me how to use it from master? I'd like to make the adapter now and would prefer to use SBUS instead of PPM?
