### ISSUE TITLE
Did not connect as Joy-HID

### ISSUE THREAD

**Issue by vatriani** [wireless-rc-adapter/wireless-rc-adapter#6]
Win10 doesn't shown up the fresh flashed arduino leonardo as an Joy-Dev.

Arduino IDE 1.6.12
Joystick 2.0.5
EEPROM 2.0.0
PinChangeInterrupt 1.2.6

After changing the constructor for Joystick_ in line 33
`Joystick_ Joystick(JOYSTICK_DEFAULT_REPORT_ID, 
  JOYSTICK_TYPE_MULTI_AXIS, 2, 0,
  true, true, true, false, false, true,
  false, false, false, false, false);`
to
`Joystick_ Joystick;`

everythings works fine and the leonardo would apear as an generic Joydev.

**Comment by ghost** [comment]
Have you tried it on other win10 devices? 
I mean is this applies to all win10 in general?

**Comment by ultimate1112** [comment]
Some devices don't recognise JOYSTICK_TYPE_MULTI_AXIS. Try JOYSTICK_TYPE_JOYSTICK or JOYSTICK_TYPE_GAMEPAD.

**Comment by ghost** [comment]
Issue needs to be undone?
May i ask the reason you have changed that value in commit 98a17b2cb6dc7049bc17dfe445d82afa47342950 @ultimate1112 ?

**Comment by ultimate1112** [comment]
Some Windows computers, ie. Windows 7 and 8, like Joystick and Gamepad better, as it simulates an Xbox controller. Thus, more applications can utilize it.

**Comment by ghost** [comment]
Thanks for explaining!
Probably needs a 'defined switch' for that in the header, then everybody can decide which one is suitable before compiling.
